/**
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 */
import { useContext } from 'react';
import { getJB7DayReconfigurationBufferBallot } from '../../../../../core/src';

import { JuiceContext } from '../../../contexts/JuiceContext';

export function useJB7DayReconfigurationBufferBallot() {
  const { provider, networkName } = useContext(JuiceContext);
  if (!provider) return;

  return getJB7DayReconfigurationBufferBallot(provider, {
    network: networkName ?? 'mainnet',
  });
}
