/**
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 */
import { useContext } from 'react';
import { getJBSingleTokenPaymentTerminalStore } from '../../../../../core/src';

import { JuiceContext } from '../../../contexts/JuiceContext';

export function useJBSingleTokenPaymentTerminalStore() {
  const { provider, networkName } = useContext(JuiceContext);
  if (!provider) return;

  return getJBSingleTokenPaymentTerminalStore(provider, {
    network: networkName ?? 'mainnet',
  });
}
