/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface JB7DayReconfigurationBufferBallotInterface
  extends utils.Interface {
  functions: {
    "duration()": FunctionFragment;
    "stateOf(uint256,uint256,uint256)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "duration" | "stateOf" | "supportsInterface"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "duration", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "stateOf",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "duration", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stateOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;

  events: {};
}

export interface JB7DayReconfigurationBufferBallot extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: JB7DayReconfigurationBufferBallotInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    /**
     *  The number of seconds that must pass for a funding cycle reconfiguration to become either `Approved` or `Failed`.
     */
    duration(overrides?: CallOverrides): Promise<[BigNumber]>;

    /**
     *  The approval state of a particular funding cycle.
     * @param _configured The configuration of the funding cycle to check the state of.
     * @param _projectId The ID of the project to which the funding cycle being checked belongs.
     * @param _start The start timestamp of the funding cycle to check the state of.
     */
    stateOf(
      _projectId: BigNumberish,
      _configured: BigNumberish,
      _start: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    /**
     *  See {IERC165-supportsInterface}.
     * Indicates if this contract adheres to the specified interface.
     * @param _interfaceId The ID of the interface to check for adherance to.
     */
    supportsInterface(
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  /**
   *  The number of seconds that must pass for a funding cycle reconfiguration to become either `Approved` or `Failed`.
   */
  duration(overrides?: CallOverrides): Promise<BigNumber>;

  /**
   *  The approval state of a particular funding cycle.
   * @param _configured The configuration of the funding cycle to check the state of.
   * @param _projectId The ID of the project to which the funding cycle being checked belongs.
   * @param _start The start timestamp of the funding cycle to check the state of.
   */
  stateOf(
    _projectId: BigNumberish,
    _configured: BigNumberish,
    _start: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  /**
   *  See {IERC165-supportsInterface}.
   * Indicates if this contract adheres to the specified interface.
   * @param _interfaceId The ID of the interface to check for adherance to.
   */
  supportsInterface(
    _interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    /**
     *  The number of seconds that must pass for a funding cycle reconfiguration to become either `Approved` or `Failed`.
     */
    duration(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     *  The approval state of a particular funding cycle.
     * @param _configured The configuration of the funding cycle to check the state of.
     * @param _projectId The ID of the project to which the funding cycle being checked belongs.
     * @param _start The start timestamp of the funding cycle to check the state of.
     */
    stateOf(
      _projectId: BigNumberish,
      _configured: BigNumberish,
      _start: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    /**
     *  See {IERC165-supportsInterface}.
     * Indicates if this contract adheres to the specified interface.
     * @param _interfaceId The ID of the interface to check for adherance to.
     */
    supportsInterface(
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    /**
     *  The number of seconds that must pass for a funding cycle reconfiguration to become either `Approved` or `Failed`.
     */
    duration(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     *  The approval state of a particular funding cycle.
     * @param _configured The configuration of the funding cycle to check the state of.
     * @param _projectId The ID of the project to which the funding cycle being checked belongs.
     * @param _start The start timestamp of the funding cycle to check the state of.
     */
    stateOf(
      _projectId: BigNumberish,
      _configured: BigNumberish,
      _start: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     *  See {IERC165-supportsInterface}.
     * Indicates if this contract adheres to the specified interface.
     * @param _interfaceId The ID of the interface to check for adherance to.
     */
    supportsInterface(
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     *  The number of seconds that must pass for a funding cycle reconfiguration to become either `Approved` or `Failed`.
     */
    duration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     *  The approval state of a particular funding cycle.
     * @param _configured The configuration of the funding cycle to check the state of.
     * @param _projectId The ID of the project to which the funding cycle being checked belongs.
     * @param _start The start timestamp of the funding cycle to check the state of.
     */
    stateOf(
      _projectId: BigNumberish,
      _configured: BigNumberish,
      _start: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     *  See {IERC165-supportsInterface}.
     * Indicates if this contract adheres to the specified interface.
     * @param _interfaceId The ID of the interface to check for adherance to.
     */
    supportsInterface(
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
